version: '2'

services:
  webdav:
    image: webdav:latest
    volumes:
      - /mnt/data/nas_data:/media
    environment:
      - VIRTUAL_HOST=webdav.zgray.com
    restart: always
    network_mode: bridge
  aria2:
    image: aria2-ariang-docker:latest
    ports:
      # - "80:80"
      # - "443:443"
      - "6801:6800"
    volumes:
      - /mnt/data/nas_data:/data
      - aria2-conf:/root/conf
    environment:
      - VIRTUAL_HOST=ariang.zgray.com
    links:
      - webdav
    restart: always
    network_mode: bridge
volumes:
  aria2-conf: